name: SPHeRe
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=22.0
  - pytorch==2.0.1
  - torchvision==0.15.2
  - cudatoolkit
  - numpy<2
  - matplotlib
  - tqdm
